dist: focal
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
      - cmake
      - cmake-data
before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.19/cmake-3.19.0-rc3-Linux-x86_64.sh
  - chmod +x cmake-3.19.0-rc3-Linux-x86_64.sh
  - ./cmake-3.19.0-rc3-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
script:
  # Link gcc-10 and g++-10 to their standard commands
  - sudo ln -s /usr/bin/gcc-10 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-10 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-10
  - export CXX=/usr/bin/g++-10
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cmake -H. -Bbuild
  - cmake --build ./build