#include "ScriptedLocalisations.h"



std::string HoI4::ScriptedLocalisations::getLocalisations() const
{
	std::string localisations;
	localisations += "defined_text = { # Country\n";
	localisations += "name = GetStrengthRatioBritain\n";
	localisations += "text = {\n";
	localisations += "trigger = { \n";
	localisations += "if = { \n";
	localisations += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = ENG\n";
	localisations += "ratio < 1\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = ENG\n";
	localisations += "ratio > 0.9\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "else_if = { \n";
	localisations += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = USA\n";
	localisations += "ratio < 1\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = USA\n";
	localisations += "ratio > 0.9\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "localization_key = Naval_treaty_90\n";
	localisations += "}\n";
	localisations += "text = { \n";
	localisations += "trigger = { \n";
	localisations += "if = { \n";
	localisations += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = ENG\n";
	localisations += "ratio < 0.9\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = ENG\n";
	localisations += "ratio > 0.75\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "else_if = { \n";
	localisations += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = USA\n";
	localisations += "ratio < 0.9\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = USA\n";
	localisations += "ratio > 0.75\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "localization_key = Naval_treaty_75\n";
	localisations += "}\n";
	localisations += "text = { \n";
	localisations += "trigger = { \n";
	localisations += "if = { \n";
	localisations += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = ENG\n";
	localisations += "ratio < 0.75\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = ENG\n";
	localisations += "ratio > 0.5\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "					battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "else_if = { \n";
	localisations += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	localisations += "			naval_strength_comparison = { \n";
	localisations += "other = USA\n";
	localisations += "ratio < 0.75\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = USA\n";
	localisations += "ratio > 0.5\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "localization_key = Naval_treaty_50\n";
	localisations += "}\n";
	localisations += "text = { \n";
	localisations += "trigger = { \n";
	localisations += "if = { \n";
	localisations += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = ENG\n";
	localisations += "ratio < 0.5\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "else_if = { \n";
	localisations += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = USA\n";
	localisations += "ratio < 0.5\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "localization_key = Naval_treaty_lower_than_50\n";
	localisations += "}\n";
	localisations += "text = { \n";
	localisations += "trigger = { \n";
	localisations += "if = { \n";
	localisations += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = ENG\n";
	localisations += "ratio > 1\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "else_if = { \n";
	localisations += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	localisations += "naval_strength_comparison = { \n";
	localisations += "other = USA\n";
	localisations += "ratio > 1\n";
	localisations += "sub_unit_def_weights = { \n";
	localisations += "carrier = 0.5\n";
	localisations += "battleship = 1\n";
	localisations += "battle_cruiser = 0.8\n";
	localisations += "heavy_cruiser = 0.5\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "localization_key = Naval_treaty_over_100\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "defined_text = { # Country\n";
	localisations += "name = GetRelevantNavalTreatyNation\n";
	localisations += "text = { \n";
	localisations += "trigger = { \n";
	localisations += "ENG = { \n";
	localisations += "has_naval_treaty_trigger = yes\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "localization_key = ENG_Naval_treaty_nation\n";
	localisations += "}\n";
	localisations += "text = { \n";
	localisations += "trigger = { \n";
	localisations += "ENG = { \n";
	localisations += "not = { has_naval_treaty_trigger = yes }\n";
	localisations += "}\n";
	localisations += "USA = { \n";
	localisations += "has_naval_treaty_trigger = yes\n";
	localisations += "}\n";
	localisations += "}\n";
	localisations += "localization_key = USA_Naval_treaty_nation\n";
	localisations += "}\n";
	localisations += "}\n";

	return localisations;
}
