#include "ScriptedLocalisations.h"



HoI4::ScriptedLocalisations::ScriptedLocalisations()
{
	ScriptedLocalisation GetStrengthRatioBritain;
	GetStrengthRatioBritain.setName("GetStrengthRatioBritain");
	std::string text;
	text += "trigger = { \n";
	text += "if = { \n";
	text += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = ENG\n";
	text += "ratio < 1\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "naval_strength_comparison = { \n";
	text += "other = ENG\n";
	text += "ratio > 0.9\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "else_if = { \n";
	text += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = USA\n";
	text += "ratio < 1\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "naval_strength_comparison = { \n";
	text += "other = USA\n";
	text += "ratio > 0.9\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "localization_key = Naval_treaty_90\n";
	GetStrengthRatioBritain.addText(text);

	text = "trigger = { \n";
	text += "if = { \n";
	text += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = ENG\n";
	text += "ratio < 0.9\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "naval_strength_comparison = { \n";
	text += "other = ENG\n";
	text += "ratio > 0.75\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "else_if = { \n";
	text += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = USA\n";
	text += "ratio < 0.9\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "naval_strength_comparison = { \n";
	text += "other = USA\n";
	text += "ratio > 0.75\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "localization_key = Naval_treaty_75\n";
	GetStrengthRatioBritain.addText(text);

	text = "trigger = { \n";
	text += "if = { \n";
	text += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = ENG\n";
	text += "ratio < 0.75\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "naval_strength_comparison = { \n";
	text += "other = ENG\n";
	text += "ratio > 0.5\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "					battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "else_if = { \n";
	text += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	text += "			naval_strength_comparison = { \n";
	text += "other = USA\n";
	text += "ratio < 0.75\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "naval_strength_comparison = { \n";
	text += "other = USA\n";
	text += "ratio > 0.5\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "localization_key = Naval_treaty_50\n";
	GetStrengthRatioBritain.addText(text);

	text = "trigger = { \n";
	text += "if = { \n";
	text += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = ENG\n";
	text += "ratio < 0.5\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "else_if = { \n";
	text += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = USA\n";
	text += "ratio < 0.5\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "localization_key = Naval_treaty_lower_than_50\n";
	GetStrengthRatioBritain.addText(text);

	text = "trigger = { \n";
	text += "if = { \n";
	text += "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = ENG\n";
	text += "ratio > 1\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "else_if = { \n";
	text += "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	text += "naval_strength_comparison = { \n";
	text += "other = USA\n";
	text += "ratio > 1\n";
	text += "sub_unit_def_weights = { \n";
	text += "carrier = 0.5\n";
	text += "battleship = 1\n";
	text += "battle_cruiser = 0.8\n";
	text += "heavy_cruiser = 0.5\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "}\n";
	text += "localization_key = Naval_treaty_over_100\n";
	GetStrengthRatioBritain.addText(text);
	scriptedLocalistions.push_back(GetStrengthRatioBritain);

	ScriptedLocalisation GetRelevantNavalTreatyNation;
	GetRelevantNavalTreatyNation.setName("GetRelevantNavalTreatyNation");
	text = "trigger = { \n";
	text += "ENG = { \n";
	text += "has_naval_treaty_trigger = yes\n";
	text += "}\n";
	text += "}\n";
	text += "localization_key = ENG_Naval_treaty_nation\n";
	GetRelevantNavalTreatyNation.addText(text);

	text = "trigger = { \n";
	text += "ENG = { \n";
	text += "not = { has_naval_treaty_trigger = yes }\n";
	text += "}\n";
	text += "USA = { \n";
	text += "has_naval_treaty_trigger = yes\n";
	text += "}\n";
	text += "}\n";
	text += "localization_key = USA_Naval_treaty_nation\n";
	GetRelevantNavalTreatyNation.addText(text);
	scriptedLocalistions.push_back(GetRelevantNavalTreatyNation);
}
