#include "ScriptedLocalisationsOutputter.h"
#include <fstream>



void HoI4::outputScriptedLocalisations(const Configuration& theConfiguration)
{
	std::ofstream scriptedLocalisationsFile(
		"output/" + theConfiguration.getOutputName() + "/common/scripted_localisation/00_scripted_localisation.txt",
		std::ofstream::app
	);

	scriptedLocalisationsFile << "defined_text = { # Country\n";
	scriptedLocalisationsFile << "name = GetStrengthRatioBritain\n";
	scriptedLocalisationsFile << "text = {\n";
	scriptedLocalisationsFile << "trigger = { \n";
	scriptedLocalisationsFile << "if = { \n";
	scriptedLocalisationsFile << "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = ENG\n";
	scriptedLocalisationsFile << "ratio < 1\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = ENG\n";
	scriptedLocalisationsFile << "ratio > 0.9\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "else_if = { \n";
	scriptedLocalisationsFile << "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = USA\n";
	scriptedLocalisationsFile << "ratio < 1\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = USA\n";
	scriptedLocalisationsFile << "ratio > 0.9\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "localization_key = Naval_treaty_90\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "text = { \n";
	scriptedLocalisationsFile << "trigger = { \n";
	scriptedLocalisationsFile << "if = { \n";
	scriptedLocalisationsFile << "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = ENG\n";
	scriptedLocalisationsFile << "ratio < 0.9\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = ENG\n";
	scriptedLocalisationsFile << "ratio > 0.75\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "else_if = { \n";
	scriptedLocalisationsFile << "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = USA\n";
	scriptedLocalisationsFile << "ratio < 0.9\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = USA\n";
	scriptedLocalisationsFile << "ratio > 0.75\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "localization_key = Naval_treaty_75\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "text = { \n";
	scriptedLocalisationsFile << "trigger = { \n";
	scriptedLocalisationsFile << "if = { \n";
	scriptedLocalisationsFile << "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = ENG\n";
	scriptedLocalisationsFile << "ratio < 0.75\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = ENG\n";
	scriptedLocalisationsFile << "ratio > 0.5\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "					battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "else_if = { \n";
	scriptedLocalisationsFile << "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "			naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = USA\n";
	scriptedLocalisationsFile << "ratio < 0.75\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = USA\n";
	scriptedLocalisationsFile << "ratio > 0.5\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "localization_key = Naval_treaty_50\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "text = { \n";
	scriptedLocalisationsFile << "trigger = { \n";
	scriptedLocalisationsFile << "if = { \n";
	scriptedLocalisationsFile << "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = ENG\n";
	scriptedLocalisationsFile << "ratio < 0.5\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "else_if = { \n";
	scriptedLocalisationsFile << "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = USA\n";
	scriptedLocalisationsFile << "ratio < 0.5\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "localization_key = Naval_treaty_lower_than_50\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "text = { \n";
	scriptedLocalisationsFile << "trigger = { \n";
	scriptedLocalisationsFile << "if = { \n";
	scriptedLocalisationsFile << "limit = { ENG = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = ENG\n";
	scriptedLocalisationsFile << "ratio > 1\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "else_if = { \n";
	scriptedLocalisationsFile << "limit = { USA = { has_naval_treaty_trigger = yes } }\n";
	scriptedLocalisationsFile << "naval_strength_comparison = { \n";
	scriptedLocalisationsFile << "other = USA\n";
	scriptedLocalisationsFile << "ratio > 1\n";
	scriptedLocalisationsFile << "sub_unit_def_weights = { \n";
	scriptedLocalisationsFile << "carrier = 0.5\n";
	scriptedLocalisationsFile << "battleship = 1\n";
	scriptedLocalisationsFile << "battle_cruiser = 0.8\n";
	scriptedLocalisationsFile << "heavy_cruiser = 0.5\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "localization_key = Naval_treaty_over_100\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "defined_text = { # Country\n";
	scriptedLocalisationsFile << "name = GetRelevantNavalTreatyNation\n";
	scriptedLocalisationsFile << "text = { \n";
	scriptedLocalisationsFile << "trigger = { \n";
	scriptedLocalisationsFile << "ENG = { \n";
	scriptedLocalisationsFile << "has_naval_treaty_trigger = yes\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "localization_key = ENG_Naval_treaty_nation\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "text = { \n";
	scriptedLocalisationsFile << "trigger = { \n";
	scriptedLocalisationsFile << "ENG = { \n";
	scriptedLocalisationsFile << "not = { has_naval_treaty_trigger = yes }\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "USA = { \n";
	scriptedLocalisationsFile << "has_naval_treaty_trigger = yes\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "localization_key = USA_Naval_treaty_nation\n";
	scriptedLocalisationsFile << "}\n";
	scriptedLocalisationsFile << "}\n";
}