#include "src/HOI4World/Events/LarOccupationEvents.h"
#include <sstream>



void HoI4::updateCreateUprisingEvent(HoI4::Event& theEvent, const std::set<std::string>& majorIdeologies)
{
	std::stringstream immediateStream;
	immediateStream << "= {\n";
	immediateStream << "\t\tFROM = {\n";
	immediateStream << "\t\t\tif = {\n";
	immediateStream << "\t\t\t\tlimit = {\n";
	immediateStream << "\t\t\t\t\thas_core_occupation_modifier = {\n";
	immediateStream << "\t\t\t\t\t\toccupied_country_tag = FROM\n";
	immediateStream << "\t\t\t\t\t\tmodifier = resistance_90\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t}\n";
	immediateStream << "\t\t\t\tset_temp_variable = { occupier_country = THIS }\n";
	immediateStream << "\t\t\t\tset_temp_variable = { occupied_country = FROM }\n";
	immediateStream << "\t\t\t\tset_temp_variable = { new_occupied_country = FROM }\n";
	immediateStream << "\n";
	immediateStream << "\t\t\t\tset_temp_variable = { civil_war_country_picked = 0 }\n";
	immediateStream << "\t\t\t\tif = {\n";
	immediateStream << "\t\t\t\t\t## pick an existing civil war country\n";
	immediateStream << "\t\t\t\t\tlimit = {\n";
	immediateStream << "\t\t\t\t\t\tFROM = {\n";
	immediateStream << "\t\t\t\t\t\t\ttag = PREV\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\trandom_country_with_original_tag = {\n";
	immediateStream << "\t\t\t\t\t\toriginal_tag_to_check = var:occupier_country\n";
	immediateStream << "\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\tlimit = {\n";
	immediateStream << "\t\t\t\t\t\t\tNOT = { tag = var:occupier_country }\n";
	immediateStream << "\t\t\t\t\t\t\thas_war_with = var:occupier_country\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\tset_temp_variable = { civil_war_country_picked = 1 }\n";
	immediateStream << "\t\t\t\t\t\tset_temp_variable = { new_occupied_country = this }\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\n";
	immediateStream << "\t\t\t\tif = {\n";
	immediateStream << "\t\t\t\t\t## create a new country if necessary\n";
	immediateStream << "\t\t\t\t\tlimit = {\n";
	immediateStream << "\t\t\t\t\t\tcheck_variable = { civil_war_country_picked = 0 } \n";
	immediateStream << "\t\t\t\t\t\tFROM = {\n";
	immediateStream << "\t\t\t\t\t\t\t#if resistance country exists and not at war with occupier (whitepaced/subjected "
							 "etc) create a country instead\n";
	immediateStream << "\t\t\t\t\t\t\texists = yes\n";
	immediateStream << "\t\t\t\t\t\t\tNOT = { has_war_with = occupier_country }\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\tcreate_dynamic_country = {\n";
	immediateStream << "\t\t\t\t\t\toriginal_tag = FROM\n";
	immediateStream << "\t\t\t\t\t\tcopy_tag = FROM\n";
	immediateStream << "\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\tset_temp_variable = { new_occupied_country = THIS }\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\n";
	immediateStream << "\t\t\t\t\n";
	immediateStream << "\t\t\t\t# change ideology if necessary\n";
	immediateStream << "\t\t\t\tif = {\n";
	immediateStream << "\t\t\t\t\tlimit = { \n";
	immediateStream << "\t\t\t\t\t\tvar:occupied_country = {\n";
	immediateStream
		 << "\t\t\t\t\t\t\t#only change ideology if we are not creating a new country and old country is not existing\n";
	immediateStream << "\t\t\t\t\t\t\tOR = {\n";
	immediateStream << "\t\t\t\t\t\t\t\texists = no\n";
	immediateStream << "\t\t\t\t\t\t\t\tNOT = { tag = new_occupied_country }\n";
	immediateStream << "\t\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t# booleans that will be allowed to change ideology\n";
	for (const auto& ideology: majorIdeologies)
	{
		immediateStream << "\t\t\t\t\tset_temp_variable = { allowed_party_" << ideology << " = 1 }\n";
	}
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t# do not change ideology of occupier country\n";
	immediateStream << "\t\t\t\t\tvar:occupier_country = {\n";
	immediateStream << "\t\t\t\t\t\tremove_from_allowed_party = yes\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\tif = {\n";
	immediateStream << "\t\t\t\t\t\t# if occupied country exists and different than new country\n";
	immediateStream << "\t\t\t\t\t\t# it is white peaced & subject of occupier. ignore its ideology as well\n";
	immediateStream
		 << "\t\t\t\t\t\tlimit = { NOT = { check_variable = { new_occupied_country = occupied_country } } }\n";
	immediateStream << "\t\t\t\t\t\tvar:occupied_country = {\n";
	immediateStream << "\t\t\t\t\t\t\tremove_from_allowed_party = yes\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t# change government if necessary\n";
	immediateStream << "\t\t\t\t\tvar:new_occupied_country = {\n";
	immediateStream << "\t\t\t\t\t\trandom_list = {\n";
	for (const auto& ideology: majorIdeologies)
	{
		immediateStream << "\t\t\t\t\t\t\tallowed_party_" << ideology << " = {\n";
		immediateStream << "\t\t\t\t\t\t\t\tset_popularities = {\n";
		immediateStream << "\t\t\t\t\t\t\t\t\t" << ideology << " = 100\n";
		immediateStream << "\t\t\t\t\t\t\t\t}\n";
		immediateStream << "\t\t\t\t\t\t\t\tset_politics = { ruling_party = " << ideology
							 << " elections_allowed = " << (ideology == "democratic" ? "yes" : "no") << " }\n";
		immediateStream << "\t\t\t\t\t\t\t}\n";
	}
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\n";
	immediateStream << "\t\t\t\t# create resistance template for armies to spawn\n";
	immediateStream << "\t\t\t\tvar:new_occupied_country = {\n";
	immediateStream << "\t\t\t\t\tif = {\n";
	immediateStream << "\t\t\t\t\t\tlimit = { NOT = { has_country_flag = created_civil_war_template } }\n";
	immediateStream << "\t\t\t\t\t\tset_country_flag = created_civil_war_template\n";
	immediateStream << "\t\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\tdivision_template = {\n";
	immediateStream << "\t\t\t\t\t\t\tname = \"Resistance\"\n";
	immediateStream << "\t\t\t\t\t\t\tis_locked = yes\n";
	immediateStream << "\t\t\t\t\t\t\tregiments = {\n";
	immediateStream << "\t\t\t\t\t\t\t\tinfantry = { x = 0 y = 0 }\n";
	immediateStream << "\t\t\t\t\t\t\t\tinfantry = { x = 0 y = 1 }\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\t\t\tinfantry = { x = 1 y = 0 }\n";
	immediateStream << "\t\t\t\t\t\t\t\tinfantry = { x = 1 y = 1 }\n";
	immediateStream << "\t\t\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\t\t\tinfantry = { x = 2 y = 0 }\n";
	immediateStream << "\t\t\t\t\t\t\t\tinfantry = { x = 2 y = 1 }\n";
	immediateStream << "\t\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\n";
	immediateStream << "\t\t\t\t\n";
	immediateStream << "\t\t\t\tclear_temp_array = checked_neighbours\n";
	immediateStream << "\t\t\t\tevery_controlled_state = {\n";
	immediateStream << "\t\t\t\t\tlimit = { \n";
	immediateStream << "\t\t\t\t\t\toccupied_country_tag = occupied_country \n";
	immediateStream << "\t\t\t\t\t\timpassable = no\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t# move our armies to back home\n";
	immediateStream << "\t\t\t\t\tteleport_armies = {\n";
	immediateStream << "\t\t\t\t\t\tlimit = { \n";
	immediateStream << "\t\t\t\t\t\t\tOR = {\n";
	immediateStream << "\t\t\t\t\t\t\t\tis_ally_with = occupier_country\n";
	immediateStream << "\t\t\t\t\t\t\t\thas_military_access_to = occupier_country\n";
	immediateStream << "\t\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\tto_state_array = owned_controlled_states\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t# transfer state\n";
	immediateStream << "\t\t\t\t\tif = {\n";
	immediateStream << "\t\t\t\t\t\tlimit = { has_resistance = yes }\n";
	immediateStream << "\t\t\t\t\t\tset_resistance = 0\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\tvar:new_occupied_country = {\n";
	immediateStream << "\t\t\t\t\t\ttransfer_state = PREV\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\tif = {\n";
	immediateStream << "\t\t\t\t\t\tlimit = { \n";
	immediateStream << "\t\t\t\t\t\t\tvar:occupier_country = {\n";
	immediateStream << "\t\t\t\t\t\t\t\tcheck_variable = { resistance_already_inited@var:occupied_country = 0 } \n";
	immediateStream << "\t\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\t# create resistance units, number is relative to size of industry\n";
	immediateStream << "\t\t\t\t\t\tset_temp_variable = { num_units_to_create = building_level@arms_factory }\n";
	immediateStream
		 << "\t\t\t\t\t\tadd_to_temp_variable = { num_units_to_create = building_level@industrial_complex } \n";
	immediateStream << "\t\t\t\t\t\tdivide_temp_variable = { num_units_to_create = 3 }\n";
	immediateStream << "\t\t\t\t\t\tadd_to_temp_variable = { num_units_to_create = 2 }\n";
	immediateStream << "\t\t\t\t\t\tround_temp_variable = num_units_to_create\n";
	immediateStream << "\t\t\t\t\t\tclamp_temp_variable = { var = num_units_to_create min = 2 max = 6 }\n";
	immediateStream << "\t\t\t\t\t\tfor_loop_effect = {\n";
	immediateStream << "\t\t\t\t\t\t\tend = num_units_to_create\n";
	immediateStream << "\t\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\t\tcreate_unit = {\n";
	immediateStream << "\t\t\t\t\t\t\t\tdivision = \"division_template = \\\"Resistance\\\" start_experience_factor = 1 "
							 "start_equipment_factor = 1\"\n";
	immediateStream << "\t\t\t\t\t\t\t\towner = new_occupied_country\n";
	immediateStream << "\t\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t# also check neighboring core states of the occupier that are not captured yet\n";
	immediateStream << "\t\t\t\t\t# move our armies so they are not surrounded/create pockets\n";
	immediateStream << "\t\t\t\t\tevery_neighbor_state = {\n";
	immediateStream << "\t\t\t\t\t\tlimit = {\n";
	immediateStream << "\t\t\t\t\t\t\tis_owned_and_controlled_by = occupied_country\n";
	immediateStream << "\t\t\t\t\t\t\tis_core_of = occupied_country\n";
	immediateStream << "\t\t\t\t\t\t\tnot = { is_in_array = { checked_neighbours = this } }\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\tadd_to_temp_array = { checked_neighbours = this }\n";
	immediateStream << "\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\tteleport_armies = {\n";
	immediateStream << "\t\t\t\t\t\t\tlimit = { \n";
	immediateStream << "\t\t\t\t\t\t\t\tOR = {\n";
	immediateStream << "\t\t\t\t\t\t\t\t\tis_ally_with = occupier_country\n";
	immediateStream << "\t\t\t\t\t\t\t\t\thas_military_access_to = occupier_country\n";
	immediateStream << "\t\t\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t\tto_state_array = owned_controlled_states\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t\n";
	immediateStream << "\t\t\t\t\t\tset_state_province_controller = {\n";
	immediateStream << "\t\t\t\t\t\t\tcontroller = occupied_country\n";
	immediateStream << "\t\t\t\t\t\t\tlimit = {\n";
	immediateStream << "\t\t\t\t\t\t\t\tis_ally_with = occupier_country\n";
	immediateStream << "\t\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\t}\n";
	immediateStream << "\t\t\t\t}\n";
	immediateStream << "\t\t\t\n";
	immediateStream << "\t\t\t\t# create war if necessary\n";
	immediateStream << "\t\t\t\tif = {\n";
	immediateStream << "\t\t\t\t\tlimit = { NOT = { has_war_with = new_occupied_country } }\n";
	immediateStream << "\t\t\t\t\tdeclare_war_on = { target = new_occupied_country type = annex_everything }\n";
	immediateStream << "\t\t\t\t}\n";
	immediateStream << "\t\t\t\t\n";
	immediateStream << "\t\t\t\tvar:occupier_country = {\n";
	immediateStream << "\t\t\t\t\tset_variable = { resistance_already_inited@var:occupied_country = 1 } \n";
	immediateStream << "\t\t\t\t}\n";
	immediateStream << "\t\t\t\n";
	immediateStream << "\t\t\t}\n";
	immediateStream << "\t\t}\n";
	immediateStream << "\t}";
	theEvent.giveImmediate(immediateStream.str());
}