name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'Vic2ToHoI4/Source'
          - 'Vic2ToHoI4Tests'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.6.1
      with:
        clang-format-version: '11'
        check-path: ${{ matrix.path }}