name: ReSharper

on:
  pull_request: {}

jobs:
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: checkout
        uses: actions/checkout@v2
      
      - name: resharper
        uses: glassechidna/resharper-action@master
        with:
          solution: Vic2ToHoI4.sln
